spring:
  application:
    name: library-events-producer
  kafka:
    topic: library_events
    producer:
      bootstrap-server: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer